/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.leoandrew.aula14;
import java.util.*;

/**
 *
 * @author redwars22
 */
public class Aula14 extends javax.swing.JFrame {
    int[] array = new int[100];
    int sizeOfArray = 0;

    /**
     * Creates new form Aula14
     */
    public Aula14() {
        initComponents();
    }
    
    public void updateArrayInfo(){
        numberOfArrayElements.setText("vetor [" + sizeOfArray +"]");
        
        arrayViewer.setText("");
        
        for(int i = 0; i < sizeOfArray; i++)
            arrayViewer.setText(arrayViewer.getText() + "\n" + array[i]);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        element = new javax.swing.JSpinner();
        pushElementBtn = new javax.swing.JButton();
        popElementBtn = new javax.swing.JButton();
        sortElementsBtn = new javax.swing.JButton();
        numberOfArrayElements = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        arrayViewer = new javax.swing.JTextArea();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(element, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 67, 80, -1));

        pushElementBtn.setText("Adicionar");
        pushElementBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pushElementBtnActionPerformed(evt);
            }
        });
        getContentPane().add(pushElementBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 38, -1, -1));

        popElementBtn.setText("Remover");
        popElementBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popElementBtnActionPerformed(evt);
            }
        });
        getContentPane().add(popElementBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 67, -1, -1));

        sortElementsBtn.setText("Ordenar");
        sortElementsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortElementsBtnActionPerformed(evt);
            }
        });
        getContentPane().add(sortElementsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 96, -1, -1));

        numberOfArrayElements.setText("vetor [0]");
        getContentPane().add(numberOfArrayElements, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 15, -1, -1));

        arrayViewer.setColumns(20);
        arrayViewer.setRows(5);
        jScrollPane2.setViewportView(arrayViewer);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 38, 171, 158));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pushElementBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pushElementBtnActionPerformed
        // TODO add your handling code here:
        String value = String.valueOf(element.getValue());
        
        array[sizeOfArray] = Integer.parseInt(value);
        sizeOfArray++;
        updateArrayInfo();
    }//GEN-LAST:event_pushElementBtnActionPerformed

    private void popElementBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popElementBtnActionPerformed
        // TODO add your handling code here:
        if(!(sizeOfArray < 1)){
            array[sizeOfArray] = 0;
            sizeOfArray--;
            updateArrayInfo();
        }
    }//GEN-LAST:event_popElementBtnActionPerformed

    private void sortElementsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortElementsBtnActionPerformed
        // TODO add your handling code here:
        Arrays.sort(array, 0, sizeOfArray);
        
        
        updateArrayInfo();
    }//GEN-LAST:event_sortElementsBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Aula14.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Aula14.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Aula14.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Aula14.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Aula14().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea arrayViewer;
    private javax.swing.JSpinner element;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel numberOfArrayElements;
    private javax.swing.JButton popElementBtn;
    private javax.swing.JButton pushElementBtn;
    private javax.swing.JButton sortElementsBtn;
    // End of variables declaration//GEN-END:variables
}
