/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.leoandrew.prova1;

import java.util.Arrays;
import javax.swing.DefaultListModel;

/**
 *
 * @author redwars22
 */
public class Prova1 extends javax.swing.JFrame {
    
    DefaultListModel model = new DefaultListModel();
    
    double total;

    /**
     * Creates new form Prova1
     */
    public Prova1() {
        initComponents();
        setTitle("Gerador de números para a MegaSena");
        setSize(450, 450);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lengthSpinner = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        list = new javax.swing.JList<>();
        jLabel7 = new javax.swing.JLabel();
        generateButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        totalValueLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Número de dezenas");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 19, -1, -1));

        lengthSpinner.setValue(6);
        lengthSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                lengthSpinnerStateChanged(evt);
            }
        });
        getContentPane().add(lengthSpinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 16, -1, -1));

        jLabel2.setText("Valores");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 113, -1, -1));

        jLabel3.setText("6 numeros: R$ 4,50");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 136, -1, -1));

        jLabel4.setText("7 números: R$ 31,50");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 159, -1, -1));

        jLabel5.setText("8 números: R$ 126,00");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 182, -1, -1));

        jLabel6.setText("9 números: R$ 378,00");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 205, -1, -1));

        list.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(list);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 79, 173, 143));

        jLabel7.setText("Jogos anteriores");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        generateButton.setText("Gerar");
        generateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateButtonActionPerformed(evt);
            }
        });
        getContentPane().add(generateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 6, -1, -1));

        clearButton.setText("Limpar");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });
        getContentPane().add(clearButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 38, -1, -1));

        totalValueLabel.setText("Valor da aposta: R$ 0,00");
        getContentPane().add(totalValueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 240, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lengthSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_lengthSpinnerStateChanged
        // TODO add your handling code here:
        if(Integer.parseInt(String.valueOf(lengthSpinner.getValue())) < 6)
            lengthSpinner.setValue(6);
        
        if(Integer.parseInt(String.valueOf(lengthSpinner.getValue())) > 9)
            lengthSpinner.setValue(9);
    }//GEN-LAST:event_lengthSpinnerStateChanged

    private void generateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateButtonActionPerformed
        // TODO add your handling code here:
        int length = Integer.parseInt(String.valueOf(lengthSpinner.getValue()));
        int[] numbers = new int[9];
        
        for(int i = 0; i < length; i++){
            int random = (int) Math.round(Math.random() * (60.0 - 1.0) + 1.0);
            
            //Verifica se o número já existe no array
            for(int j = 0; j < i; j++){
                while(random == numbers[j]){
                    random = (int) Math.round(Math.random() * (60.0 - 1.0) + 1.0);
                }
            }
            
            numbers[i] = random;
        }
        
        
        Arrays.sort(numbers, 0, length);
        
        String listItem = "";
        
        for(int k = 0; k < length; k++){
            listItem += (String.valueOf(numbers[k]) + " ");   
        }
        
        model.addElement(listItem); 
        list.setModel(model);
        
        double price = 0.00;
        
        if(length == 6) price = 4.50;
        if(length == 7) price = 31.50;
        if(length == 8) price = 126.00;
        if(length == 9) price = 378.00;
        
        total += price;
        totalValueLabel.setText("Valor da aposta: R$ " + total);
    }//GEN-LAST:event_generateButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        // TODO add your handling code here:
        model.clear();
        list.setModel(model);
        totalValueLabel.setText("Valor da aposta: R$ 0,00");
        total = 0.00;
    }//GEN-LAST:event_clearButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Prova1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Prova1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Prova1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Prova1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Prova1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearButton;
    private javax.swing.JButton generateButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner lengthSpinner;
    private javax.swing.JList<String> list;
    private javax.swing.JLabel totalValueLabel;
    // End of variables declaration//GEN-END:variables
}
