/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lpg.imc;

import java.lang.Double;

/**
 *
 * @author madatech
 */
public class IMC extends javax.swing.JFrame {

    /**
     * Creates new form IMC
     */
    public IMC() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        calcular = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        male = new javax.swing.JRadioButton();
        female = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        situacao = new javax.swing.JLabel();
        imc_total = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        altura = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        peso = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        calcular.setText("Calcular");
        calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularActionPerformed(evt);
            }
        });
        getContentPane().add(calcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 36, -1, -1));

        jButton2.setText("Limpar");
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 72, 90, -1));

        male.setText("Masculino");
        getContentPane().add(male, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 37, -1, -1));

        female.setText("Feminino");
        getContentPane().add(female, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 73, -1, -1));

        jLabel1.setText("Sexo");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 39, -1, -1));

        jLabel2.setText("CALCULADORA DE IMC");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 6, -1, -1));

        jLabel3.setText("Altura");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        jLabel4.setText("Peso");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        jLabel5.setText("Situação:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, -1, -1));

        situacao.setText("---");
        getContentPane().add(situacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 170, 20));

        imc_total.setText("IMC: 0");
        getContentPane().add(imc_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, -1, -1));

        jScrollPane1.setViewportView(altura);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 110, -1));

        jScrollPane2.setViewportView(peso);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 100, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void calcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularActionPerformed
        // TODO add your handling code here:
        char gender = '_';
        
        if(male.isSelected()) gender = 'M';
        else if(female.isSelected()) gender = 'F';
        
        double weight = Double.parseDouble(peso.getText());
        double height = Double.parseDouble(altura.getText());
        
        double IMC = weight / Math.pow(height, 2);
        
        if(gender == 'M'){
            if(IMC < 20.7){
                situacao.setText("ABAIXO DO PESO");
            } else if(IMC < 20.7 && IMC > 26.4){
                situacao.setText("NO PESO NORMAL");
            } else if(IMC < 26.4 && IMC > 27.8){
                situacao.setText("LIGEIRAMENTE ACIMA DO PESO");
            }
             else if(IMC < 27.8 && IMC > 31.1){
                situacao.setText("ACIMA DO PESO IDEAL");
            }
             else if(IMC > 31.1){
                situacao.setText("OBESO");
            }
        } else if(gender == 'F'){
            if(IMC < 19.1){
                situacao.setText("ABAIXO DO PESO");
            } else if(IMC < 19.1 && IMC > 25.8){
                situacao.setText("NO PESO NORMAL");
            } else if(IMC < 25.8 && IMC > 27.3){
                situacao.setText("LIGEIRAMENTE ACIMA DO PESO");
            }
             else if(IMC < 27.3 && IMC > 32.3){
                situacao.setText("ACIMA DO PESO IDEAL");
            }
             else if(IMC > 32.3){
                situacao.setText("OBESO");
            }
        }
        
        imc_total.setText("IMC: " + IMC);
    }//GEN-LAST:event_calcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IMC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IMC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IMC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IMC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IMC().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane altura;
    private javax.swing.JButton calcular;
    private javax.swing.JRadioButton female;
    private javax.swing.JLabel imc_total;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton male;
    private javax.swing.JTextPane peso;
    private javax.swing.JLabel situacao;
    // End of variables declaration//GEN-END:variables
}
